export const categoriesWithTitles = [
    { id: 'toplists', name: 'Top Lists', title: "The Best of the Best: Top Lists" },
    { id: '0JQ5DAqbMKFLIOWOrpNSUR', name: 'Vietnamese Music', title: "The Heart of Vietnam: Traditional and Modern Tunes" },
    { id: '0JQ5DAqbMKFGvOw3O4nLAf', name: 'K-Pop', title: "K-Pop Craze: From Seoul to the World" },
    { id: '0JQ5DAqbMKFEC4WFtoNRpw', name: 'Pop', title: "Pop Culture Anthems: Catchy and Trending" },
    { id: '0JQ5DAqbMKFzHmL4tf05da', name: 'Mood', title: "Mood Setters: Music for Every Emotion" },
    { id: '0JQ5DAqbMKFAUsdyVjCQuL', name: 'Romance', title: "Love in Melody: Romantic Favorites" },
    { id: '0JQ5DAqbMKFImHYGo3eTSg', name: 'Fresh Finds', title: "New Beats: Discover the Latest Hits" },
    { id: '0JQ5DAqbMKFPw634sFwguI', name: 'EQUAL', title: "EQUAL Voices: Celebrating Diversity in Music" },
    { id: '0JQ5DAqbMKFLb2EqgLtpjC', name: 'Wellness', title: "Wellness Waves: Music for Health and Harmony" },
    { id: '0JQ5DAqbMKFDXXwE9BDJAr', name: 'Rock', title: "Rock Legends: Power Chords and Anthems" },
    { id: '0JQ5DAqbMKFQ00XGBls6ym', name: 'Hip-Hop', title: "Hip-Hop Grooves: From Old School to Trap" },
    { id: '0JQ5DAqbMKFx0uLQR2okcc', name: 'At Home', title: "At Home Jams: Cozy Tunes for Any Day" },
    { id: '0JQ5DAqbMKFLjmiZRss79w', name: 'Ambient', title: "Ambient Escapes: Calm and Serene Sounds" },
    { id: '0JQ5DAqbMKFOOxftoKZxod', name: 'RADAR', title: "RADAR: Upcoming Artists and Hidden Gems" },
    { id: '0JQ5DAqbMKFHOzuVTgTizF', name: 'Dance/Electronic', title: "Dance All Night: Electronic Beats and Rhythms" },
    { id: '0JQ5DAqbMKFCWjUTdzaG0e', name: 'Indie', title: "Indie Vibes: Discover Indie Music" },
    { id: '0JQ5DAqbMKFFgo8jQnAk7E', name: 'API Heritage Month', title: "API Heritage Month: Celebrating Asian and Pacific Islander Music" },
    { id: '0JQ5DAqbMKFA6SOHvT3gck', name: 'Party', title: "Party Time: Music to Get the Party Started" },
    { id: '0JQ5DAqbMKFFzDl7qN9Apr', name: 'Chill', title: "Chill Vibes: Relaxing Tunes for Any Occasion" },
    { id: '0JQ5DAqbMKFCuoRTxhYWow', name: 'Sleep', title: "Sleep Soundly: Music for a Restful Night" },
    { id: '0JQ5DAqbMKFAXlCG6QvYQ4', name: 'Workout', title: "Workout Beats: Pump Up Your Exercise Routine" },
    { id: '0JQ5DAqbMKFCbimwdOYlsl', name: 'Focus', title: "Focus and Concentration: Music for Productivity" },
    { id: '0JQ5DAqbMKFIVNxQgRNSg0', name: 'Decades', title: "Musical Decades: Hits from Different Eras" },
    { id: '0JQ5DAqbMKFLVaM30PMBm4', name: 'Summer', title: "Summer Vibes: Sunny and Uplifting Tunes" },
    { id: '0JQ5DAqbMKFJKoGyUMo2hE', name: 'Reggae', title: "Reggae Rhythms: Groove to the Island Beats" },
    { id: '0JQ5DAqbMKFEZPnFQSFB1T', name: 'R&B', title: "R&B Grooves: Smooth and Soulful Music" },
    { id: '0JQ5DAqbMKFxXaXKP7zcDp', name: 'Latin', title: "Latin Flavor: Hot and Spicy Music" },
    { id: '0JQ5DAqbMKFCfObibaOZbv', name: 'Gaming', title: "Gaming Soundtracks: Music for Gamers" },
    { id: '0JQ5DAqbMKFRieVZLLoo9m', name: 'Instrumental', title: "Instrumental Journeys: Music Without Words" },
    { id: '0JQ5DAqbMKFAJ5xb0fwo9m', name: 'Jazz', title: "Jazz Classics: Smooth and Sophisticated Tunes" },
    { id: '0JQ5DAqbMKFPrEiAOxgac3', name: 'Classical', title: "Classical Masterpieces: Timeless Compositions" },
    { id: '0JQ5DAqbMKFRKBHIxJ5hMm', name: 'Tastemakers', title: "Tastemakers: Music Curated by Experts" },
    { id: '0JQ5DAqbMKFRY5ok2pxXJ0', name: 'Cooking & Dining', title: "Cooking and Dining: Music for Food Lovers" },
    { id: '0JQ5DAqbMKFAQy4HL4XU2D', name: 'Travel', title: "Travel Adventures: Music from Around the World" },
    { id: '0JQ5DAqbMKFIpEuaCnimBj', name: 'Soul', title: "Soulful Serenades: Heartfelt Soul Music" },
    { id: '0JQ5DAqbMKFDBgllo2cUIN', name: 'Spotify Singles', title: "Spotify Singles: Exclusive Recordings" },
    { id: '0JQ5DAqbMKFFtlLYUHv8bT', name: 'Alternative', title: "Alternative Sounds: Off the Beaten Path" },
    { id: '0JQ5DAqbMKFQiK2EHwyjcU', name: 'Blues', title: "Bluesy Notes: Gritty and Soulful Blues Music" },
    { id: '0JQ5DAqbMKFAjfauKLOZiv', name: 'Punk', title: "Punk Rock Rebels: Raw and Energetic Music" },
    { id: '0JQ5DAqbMKFDkd668ypn6O', name: 'Metal', title: "Metal Mayhem: Headbanging and Heavy Riffs" },
    { id: '0JQ5DAqbMKFy78wprEpAjl', name: 'Folk & Acoustic', title: "Folk & Acoustic: Earthy and Authentic Sounds" },
    { id: '0JQ5DAqbMKFziKOShCi009', name: 'Anime', title: "Anime Anthems: Music from Your Favorite Shows" }
];
